version: "3.9"
   
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  web:
    restart: always
    depends_on:
      - db
    build: .
    ports:
      - 3000:8000
    env_file:
      - .env
    volumes:
      - .:/django_material_demo
    command: python manage.py runserver 0:8000

volumes:
  postgres_data:
