apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-database-to-latest
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrate-db
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
        command: ["python"]
        args: ["manage.py", "migrate"]
        envFrom:
          - configMapRef:
              name: env
          - configMapRef:
              name: secrets
